services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
