// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voucher"
                ],
                "summary": "Check if voucher already exists",
                "parameters": [
                    {
                        "description": "Flight info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/generate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Voucher"
                ],
                "summary": "Generate 3 random voucher seats",
                "parameters": [
                    {
                        "description": "Voucher input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.GenerateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.StatusConflictResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CheckRequest": {
            "type": "object",
            "required": [
                "date",
                "flight_number"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2025-07-12"
                },
                "flight_number": {
                    "type": "string",
                    "example": "GA102"
                }
            }
        },
        "handler.CheckResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean",
                    "example": true
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.GenerateRequest": {
            "type": "object",
            "required": [
                "aircraft",
                "date",
                "flight_number",
                "id",
                "name"
            ],
            "properties": {
                "aircraft": {
                    "type": "string",
                    "example": "Airbus 320"
                },
                "date": {
                    "type": "string",
                    "example": "2025-07-12"
                },
                "flight_number": {
                    "type": "string",
                    "example": "ID102"
                },
                "id": {
                    "type": "string",
                    "example": "98123"
                },
                "name": {
                    "type": "string",
                    "example": "Sarah"
                }
            }
        },
        "handler.GenerateResponse": {
            "type": "object",
            "properties": {
                "seats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "3B",
                        "7C",
                        "14D"
                    ]
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.StatusConflictResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "vouchers already generated"
                }
            }
        },
        "handler.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "aircraft": "aircraft type not valid",
                        "date": "date is required",
                        "flight_number": "flight_number is required"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Airline Voucher API",
	Description:      "API for generating and checking airline voucher seats",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
