// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"github.com/ibadi-id/airline-seat-assignment/backend/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVoucherUsecase creates a new instance of MockVoucherUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoucherUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoucherUsecase {
	mock := &MockVoucherUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVoucherUsecase is an autogenerated mock type for the VoucherUsecase type
type MockVoucherUsecase struct {
	mock.Mock
}

type MockVoucherUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoucherUsecase) EXPECT() *MockVoucherUsecase_Expecter {
	return &MockVoucherUsecase_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockVoucherUsecase
func (_mock *MockVoucherUsecase) Check(flightNumber string, date string) (bool, error) {
	ret := _mock.Called(flightNumber, date)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(flightNumber, date)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(flightNumber, date)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(flightNumber, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoucherUsecase_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockVoucherUsecase_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - flightNumber string
//   - date string
func (_e *MockVoucherUsecase_Expecter) Check(flightNumber interface{}, date interface{}) *MockVoucherUsecase_Check_Call {
	return &MockVoucherUsecase_Check_Call{Call: _e.mock.On("Check", flightNumber, date)}
}

func (_c *MockVoucherUsecase_Check_Call) Run(run func(flightNumber string, date string)) *MockVoucherUsecase_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVoucherUsecase_Check_Call) Return(b bool, err error) *MockVoucherUsecase_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockVoucherUsecase_Check_Call) RunAndReturn(run func(flightNumber string, date string) (bool, error)) *MockVoucherUsecase_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockVoucherUsecase
func (_mock *MockVoucherUsecase) Generate(v domain.Voucher) ([]string, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Voucher) ([]string, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Voucher) []string); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Voucher) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVoucherUsecase_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockVoucherUsecase_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - v domain.Voucher
func (_e *MockVoucherUsecase_Expecter) Generate(v interface{}) *MockVoucherUsecase_Generate_Call {
	return &MockVoucherUsecase_Generate_Call{Call: _e.mock.On("Generate", v)}
}

func (_c *MockVoucherUsecase_Generate_Call) Run(run func(v domain.Voucher)) *MockVoucherUsecase_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Voucher
		if args[0] != nil {
			arg0 = args[0].(domain.Voucher)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVoucherUsecase_Generate_Call) Return(strings []string, err error) *MockVoucherUsecase_Generate_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockVoucherUsecase_Generate_Call) RunAndReturn(run func(v domain.Voucher) ([]string, error)) *MockVoucherUsecase_Generate_Call {
	_c.Call.Return(run)
	return _c
}
